name: Java CI with Maven on View

on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Branch to build'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest  # 运行在最新的Ubuntu虚拟机上

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 检出代码仓库
        with:
          ref: ${{ github.event.inputs.branchName }}

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'  # 根据需要设置Java版本
          distribution: 'temurin'

      - name: Build with Maven spotless
        run: mvn clean spotless:apply  # 使用Maven构建项目，跳过测试

      - name: Build with Maven package
        run: mvn clean package -pl seatunnel-dist -am -Dmaven.test.skip=true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: apache-seatunnel-2.3.5-bin
          path: seatunnel-dist/target/apache-seatunnel-${{ github.event.inputs.branchName }}-bin.tar.gz
          retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

      - name: Clean up intermediate files
        run: |
          rm -rf target